### ISSUE TITLE
[bug] - no-max branch readibility of Mixer track on black over black

### ISSUE THREAD

**Issue by Nipaleme** [etiennedemoulin/midi-mixer#6]

**Comment by Nipaleme** [comment]
see PR : https://github.com/etiennedemoulin/midi-mixer/pull/7

**Comment by etiennedemoulin** [comment]
can't reproduce on my side :( what's your OS and navigator ??

**Comment by Nipaleme** [comment]
before  :
<img width="1840" alt="Screenshot 2023-10-20 at 11 34 46" src="https://github.com/etiennedemoulin/midi-mixer/assets/64738048/a692d3e9-c368-4e44-ab16-f6ef797efcf4">

**Comment by Nipaleme** [comment]
after : 
<img width="1840" alt="Screenshot 2023-10-20 at 11 32 11" src="https://github.com/etiennedemoulin/midi-mixer/assets/64738048/7616baf3-75df-44db-b168-80733c65367a">

**Comment by Nipaleme** [comment]
Mac OS Sonoma, same display on firefox and Chromium

**Comment by b-ma** [comment]
Hey, this is a bit weird, but actually it looks like you are missing a global stylesheet (the whole background should be black if I remember well)

@etiennedemoulin maybe you could check two things:
- that the css file are correctly built at install? (they should be located in `.build/public/css`)
- update to latest sc-components as well, I think I have made some fixes so they are more robust to these kind of issue

**Comment by etiennedemoulin** [comment]
was because of npm build:production, I will remove this command
